export const products = [
  {
    id: 1,
    img: "./assets/soft-sofa.png",
    name: "Vivian Sofa",
    stock: 1,
    year: 2022,
    company: "Ikea",
    color: "Grey",
    size: 107,
    popular: false,
  },
  {
    id: 2,
    img: "./assets/desk-lamp.png",
    name: "Desk lamp",
    stock: 7,
    year: 2022,
    company: "Kartell",
    color: "Beige",
    size: 15,
    popular: false,
  },

  {
    id: 3,
    img: "./assets/lamp-light.png",
    name: "Rapallo lamp",
    stock: 25,
    year: 2020,
    company: "Dunelm",
    color: "Brown",
    size: 30,
    popular: false,
  },
  {
    id: 4,
    img: "./assets/pixar-lamp.png",
    name: "Pixar lamp",
    stock: 10,
    year: 2019,
    company: "Ikea",
    color: "Grey",
    size: 10,
    popular: false,
  },
  {
    id: 5,
    img: "./assets/big-sofa.png",
    name: "Indi sofa",
    stock: 5,
    year: 2021,
    company: "Kartell",
    color: "Grey",
    size: 135,
    popular: true,
  },
  {
    id: 6,
    img: "./assets/armchair.png",
    name: "Montreal armchair",
    stock: 23,
    year: 2021,
    company: "Ashley",
    color: "Beige",
    size: 70,
    popular: true,
  },
  {
    id: 7,
    img: "./assets/lounge-chair.png",
    name: "Lounge chair",
    stock: 3,
    year: 2021,
    company: "Ashley",
    color: "Yellow",
    size: 50,
    popular: true,
  },
  {
    id: 8,
    img: "./assets/clock.png",
    name: "Kendall clock",
    stock: 5,
    year: 2019,
    company: "Kartell",
    color: "White",
    size: 10,
    popular: false,
  },
  {
    id: 9,
    img: "./assets/sofa-blue.png",
    name: "Carys sofa",
    stock: 2,
    year: 2020,
    company: "Dunelm",
    color: "Blue",
    size: 110,
    popular: true,
  },
  {
    id: 10,
    img: "./assets/tables.png",
    name: "Bromley table",
    stock: 8,
    year: 2020,
    company: "Ikea",
    color: "Brown",
    size: 54,
    popular: false,
  },
  {
    id: 11,
    img: "./assets/wood-table.png",
    name: "Fitzgerald table",
    stock: 13,
    year: 2022,
    company: "Ikea",
    color: "Brown",
    size: 65,
    popular: true,
  },
  {
    id: 12,
    img: "./assets/vase.png",
    name: "Fulton vase",
    stock: 15,
    year: 2022,
    company: "Ikea",
    color: "Grey",
    size: 8,
    popular: false,
  },
  {
    id: 13,
    img: "./assets/silver-ball.png",
    name: "Silver vase",
    stock: 5,
    year: 2019,
    company: "Ashley",
    color: "Black",
    size: 6,
    popular: false,
  },
  {
    id: 14,
    img: "./assets/steel-sofa.png",
    name: "Franco sofa",
    stock: 5,
    year: 2019,
    company: "Ikea",
    color: "Grey",
    size: 96,
    popular: true,
  },
  {
    id: 15,
    img: "./assets/party-table.png",
    name: "Greenwich table",
    stock: 4,
    year: 2021,
    company: "Kartell",
    color: "Brown",
    size: 54,
    popular: true,
  },
  {
    id: 16,
    img: "./assets/coffee-table-png-791716.png",
    name: "Coffee table",
    stock: 14,
    year: 2021,
    company: "Ikea",
    color: "Brown",
    size: 34,
    popular: false,
  },
  {
    id: 17,
    img: "./assets/pngfind.com-coffee-table-png-792277.png",
    name: "Burvik table",
    stock: 8,
    year: 2020,
    company: "Kartell",
    color: "White",
    size: 64,
    popular: false,
  },
  {
    id: 18,
    img: "./assets/pngfind.com-sofa-png-82263.png",
    name: "Rian sofa",
    stock: 6,
    year: 2021,
    company: "Ikea",
    color: "Yellow",
    size: 70,
    popular: false,
  },
  {
    id: 19,
    img: "./assets/pngfind.com-white-sofa-png-6425819.png",
    name: "Gladom sofa",
    stock: 9,
    year: 2019,
    company: "Ashley",
    color: "White",
    size: 40,
    popular: false,
  },
  {
    id: 20,
    img: "./assets/pngfind.com-sofa-png-82989.png",
    name: "Melltorp sofa",
    stock: 11,
    year: 2022,
    company: "Ikea",
    color: "Black",
    size: 40,
    popular: true,
  },
  {
    id: 21,
    img: "./assets/pngfind.com-side-table-png-5246313.png",
    name: "Melltorp table",
    stock: 2,
    year: 2021,
    company: "Ikea",
    color: "Brown",
    size: 20,
    popular: true,
  },
];
